### ISSUE TITLE
Consider using descMD title info rather than Fedora object label

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/goobi-robot#30]
See https://github.com/sul-dlss/dor-services-app/blob/f434ff122ec85f7a484fb1153e1bc7fcd3341baf/app/models/dor/goobi.rb#L29

Occasionally, the Fedora object label is not populated - which causes goobi-notify to fail. the object MODS would be a better source for object label, and more in keeping with our other services

**Comment by dinahhandel** [comment]
As far as I understand, and @blalbrit can confirm, this is only a change that would need to be made once, and will solve this problem going forward. There is no additional work that will need to be done to existing objects in the repository.

**Comment by blalbrit** [comment]
Confirmed - all existing data with this problem has been remediated already.

**Comment by mjgiarlo** [comment]
@blalbrit @dinahhandel Hi! I've just picked this issue up as part of the Infrastructure maintenance work cycle. I don't have too much experience working with the Goobi components, so to confirm based on the above... to the best of your understanding, this change would need to be made in `dor-services-app` rather than `goobi-robot`? (I don't see relevant code in `goobi-robot`, but given my lack of familiarity, I could very well be missing it!) Thanks. :slightly_smiling_face: 

I don't foresee this taking very long. Once a pull request is merged, I will work w/ you two to schedule/plan rolling out the code changes. Cool?

**Comment by mjgiarlo** [comment]
@blalbrit @dinahhandel @peetucket Do these records tend to have a single MODS title? If not, how should I pick which MODS title should be used? Should I use the first MODS title that is available? Or I could select a MODS title based on the value of an XML attribute? etc. Thanks for any guidance y'all can toss my way on this. (For now, I will use the first MODS title, and will adjust when I hear different.)

**Comment by peetucket** [comment]
I poked around and found an example of multiple titleInfo nodes (with the second being under a  relatedItem): e.g.  druid:bb000zn0114 

I'm guessing the first titleInfo node is the most likely to be the main one?  Or maybe look from the root of MOD element and work your way down to the main one, like this: `@druid_obj.datastreams['descMetadata'].ng_xml.css('//mods/titleInfo/title')`

Could also try the fedora object label first, and only revert to MODs titleInfo if that is missing, e.g. `@druid_obj.label || @druid_obj.datastreams['descMetadata'].ng_xml.css('//mods/titleInfo/title').text`?

**Comment by mjgiarlo** [comment]
@peetucket Hi, Peter. Once I heard back from y'all, or had a chance to peruse some sample records, I was thinking it might be prudent to suggest a strategy like the one you suggest.

For now, I'm going to pursue the following:

1. Use the first title available in the MODS XML;
2. If still unset, use the Fedora object label.

If I should use a different strategy—i.e., reversing the above order, or grabbing a different MODS title—let me know! I am happy to change course. :slightly_smiling_face:

**Comment by blalbrit** [comment]
@mjgiarlo - Registration will either produce minimal MODS (with a single title), if the user adds a label at registration time and expects to update the metadata later, or full MODS if using the MARC2MODS transform based on catkey.

The sample data to look at will be registered items: https://argo.stanford.edu/catalog?all=true&f%5Bprocessing_status_text_ssi%5D%5B%5D=Registered

For the former use-case, the example that should be standard is:
```
<mods xmlns="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="3.6" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-6.xsd">
  <titleInfo>
    <title>20100711_jpq_006.jpg</title>
  </titleInfo>
</mods>
```
With a single `titleInfo` block and single `title` within. This is the 90% use-case, and similar examples can be found at: https://argo.stanford.edu/catalog?all=true&f%5Bmetadata_source_ssi%5D%5B%5D=DOR&f%5Bprocessing_status_text_ssi%5D%5B%5D=Registered (by limiting to registered items with non-Symphony metadata)

The other flavor of data - MARC-derived MODS - can be found at https://argo.stanford.edu/catalog?all=true&f%5Bmetadata_source_ssi%5D%5B%5D=Symphony&f%5Bprocessing_status_text_ssi%5D%5B%5D=Registered

These should all be of the same format, with an opening `titleInfo` and `title` at the root of the MODS, like:
```
<mods xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.loc.gov/mods/v3" version="3.5" xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-5.xsd">
  <titleInfo>
    <title>Synthesis of Reactive Programs</title>
  </titleInfo>
```

The order of preference would be:
* label derived from MODS
* label derived from Fedora label

**Comment by mjgiarlo** [comment]
@blalbrit Excellent. Thank you! I believe the approach I've got in https://github.com/sul-dlss/dor-services-app/pull/173 should accommodate this.

**Comment by blalbrit** [comment]
@mjgiarlo anytime is fine by me, but the call here because of goobi is @dinahhandel 's.

**Comment by mjgiarlo** [comment]
Hi, @dinahhandel! I'm happy to chat about this whenever. :) (I'll be on campus next week, getting into the office around 1pm on Monday, FYI.)
